apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kupido-frontend
  name: kupido-frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-frontend
    spec:
      containers:
      - image: philipoffermansinfinity/frontend
        name: frontend
        resources: {}
status: {}
