apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kupido-frontend
  name: kupido-frontend
  namespace: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: app-frontend
