apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kupido-backend
  name: kupido-backend
  namespace: backend
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30005
  selector:
    app: kupido-backend
