apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kupido-db-pvc1
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard"
